# 두 모집단의 비교
setwd("C:/Users/김유진/Desktop/4학년 1힉기/통계분석방법/기말고사 공부")
temp = read.table("normaltemp.txt",header = T)
head(temp)
str(temp)
male = temp[(temp[,2] %in% 1),1]
female = temp[(temp[,2] %in% 2),1]
par(mfrow = c(2,1))
hist(male)
hist(female)
d1 = density(male)
d2 = density(female)
plot(d1)
plot(d2)
lines(d2,col='red',lwd=3)
legend("topright",c("",""),lty = c(1,1),lwd = 3)
abline(v = mean(data), col = 'blue', lty = 2)
qqplot(data,data)
abline(a = 0, b=1)
plot(ecdf(data), col = "", pch = NA_integer_,lwd = 2)
lines(ecdf(data),col="",pch = NA_integer_,lwd = 2)
tmp1 = rnorm(100,mean = 4,sd =1)
summary(tmp1)
qqplot(tmp1,)
abline(a=0,b=1)
#기술통계량
library(psych)
describe(data)
library(moments)
agostino.test(data)
anscombe.test(data)
#정규확률그림
qqnorm(data)
qqline(data)
#정규성 검정
library(nortest)
shapiro.test(data)
ad.test(data)
#등분산 검정
var.test(data,data)
mean1 = mean(data)
var1 = var(data)
n1 = length(data)
var_pooled = ((n-1)*var1+(n2-1)*var2)/(n1+n2-2)
t1 = (mean1-mean2)/sqrt(var_pooled&(1/n1+1/n2))
pval = 2*(1-pt(abs(t1),df=n1+n2-2))
t.test(data,data,var.equal = T)
